import type { ThemeConfig } from 'antd';
import { colors, typography } from './tokens';

export const antdTheme: ThemeConfig = {
  token: {
    colorPrimary: colors.primary,
    colorPrimaryHover: colors.primaryHover,
    colorPrimaryActive: colors.primaryActive,
    colorSuccess: colors.success,
    colorWarning: colors.warning,
    colorError: colors.error,
    colorInfo: colors.info,
    borderRadius: 6,
    borderRadiusSM: 4,
    borderRadiusLG: 10,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontSizeSM: 13,
    fontSizeLG: 16,
    controlHeight: 34,
    controlHeightSM: 30,
    controlHeightLG: 40,
    paddingContentHorizontal: 16,
    paddingContentVertical: 12,
    colorText: colors.text.primary,
    colorTextSecondary: colors.text.secondary,
    colorTextTertiary: colors.text.tertiary,
    colorTextDisabled: colors.text.disabled,
    colorBorder: colors.border,
    colorBorderSecondary: colors.borderLight,
    colorBgContainer: colors.bgElevated,
    colorBgElevated: colors.bgElevated,
    colorBgLayout: colors.bg,
    boxShadow: 'none',
    boxShadowSecondary: 'none',
    boxShadowTertiary: 'none',
  },
  components: {
    Button: {
      borderRadius: 10,
      paddingInline: 18,
      primaryShadow: 'none',
      defaultShadow: 'none',
      fontWeight: 500,
    },
    Card: {
      borderRadiusLG: 10,
      paddingLG: 20,
    },
    Drawer: {
      borderRadius: 0,
      paddingLG: 24,
    },
    Input: {
      borderRadius: 6,
      activeBorderColor: colors.borderStrong,
      hoverBorderColor: colors.borderStrong,
      activeShadow: `0 0 0 2px ${colors.interaction.focusRing}`,
    },
    InputNumber: {
      borderRadius: 6,
      activeBorderColor: colors.borderStrong,
      hoverBorderColor: colors.borderStrong,
      activeShadow: `0 0 0 2px ${colors.interaction.focusRing}`,
    },
    Menu: {
      iconSize: 17,
      iconMarginInlineEnd: 10,
      itemBorderRadius: 6,
      darkItemBg: colors.bgSidebar,
      darkSubMenuItemBg: colors.bgSidebar,
      darkItemColor: colors.interaction.sidebarText,
      darkItemHoverBg: colors.interaction.sidebarHoverBg,
      darkItemSelectedBg: colors.interaction.sidebarSelectedBg,
      darkItemSelectedColor: colors.text.inverse,
    },
    Progress: {
      lineBorderRadius: 999,
      defaultColor: colors.signature.coral,
      remainingColor: colors.interaction.progressTrack,
    },
    Select: {
      borderRadius: 6,
      optionSelectedBg: colors.primaryBg,
    },
    Table: {
      borderRadius: 10,
      headerBg: colors.interaction.tableHeader,
      headerColor: colors.text.tertiary,
      rowHoverBg: colors.interaction.tableHover,
      padding: 12,
      paddingXS: 8,
      paddingSM: 8,
      fontSize: 13,
      fontSizeSM: 12,
      borderColor: colors.borderLight,
    },
    Tabs: {
      borderRadius: 8,
      margin: 0,
      itemSelectedColor: colors.primary,
      itemHoverColor: colors.primary,
      inkBarColor: colors.primary,
    },
    Tag: {
      borderRadiusSM: 4,
      defaultBg: colors.bgElevated,
      defaultColor: colors.text.secondary,
      solidTextColor: colors.text.inverse,
    },
  },
};
